// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dewPoint
float dewPoint(float celsius, float humidity);
RcppExport SEXP biometeoR_dewPoint(SEXP celsiusSEXP, SEXP humiditySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< float >::type celsius(celsiusSEXP);
    Rcpp::traits::input_parameter< float >::type humidity(humiditySEXP);
    rcpp_result_gen = Rcpp::wrap(dewPoint(celsius, humidity));
    return rcpp_result_gen;
END_RCPP
}
// es
double es(double ta);
RcppExport SEXP biometeoR_es(SEXP taSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ta(taSEXP);
    rcpp_result_gen = Rcpp::wrap(es(ta));
    return rcpp_result_gen;
END_RCPP
}
// degsat
double degsat(double t, double rh, double pa);
RcppExport SEXP biometeoR_degsat(SEXP tSEXP, SEXP rhSEXP, SEXP paSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type pa(paSEXP);
    rcpp_result_gen = Rcpp::wrap(degsat(t, rh, pa));
    return rcpp_result_gen;
END_RCPP
}
// heatindex
double heatindex(double t, double rh);
RcppExport SEXP biometeoR_heatindex(SEXP tSEXP, SEXP rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    rcpp_result_gen = Rcpp::wrap(heatindex(t, rh));
    return rcpp_result_gen;
END_RCPP
}
// p_vap
double p_vap(double t, double rh);
RcppExport SEXP biometeoR_p_vap(SEXP tSEXP, SEXP rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    rcpp_result_gen = Rcpp::wrap(p_vap(t, rh));
    return rcpp_result_gen;
END_RCPP
}
// metabolism
double metabolism(double t);
RcppExport SEXP biometeoR_metabolism(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(metabolism(t));
    return rcpp_result_gen;
END_RCPP
}
// frostime
double frostime(double t, double wind);
RcppExport SEXP biometeoR_frostime(SEXP tSEXP, SEXP windSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    rcpp_result_gen = Rcpp::wrap(frostime(t, wind));
    return rcpp_result_gen;
END_RCPP
}
// p_saturazione
double p_saturazione(double t);
RcppExport SEXP biometeoR_p_saturazione(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(p_saturazione(t));
    return rcpp_result_gen;
END_RCPP
}
// pmv_hoppe_iso
double pmv_hoppe_iso(double t, double rh, double wind, double mtrad, double iclo);
RcppExport SEXP biometeoR_pmv_hoppe_iso(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP, SEXP mtradSEXP, SEXP icloSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type mtrad(mtradSEXP);
    Rcpp::traits::input_parameter< double >::type iclo(icloSEXP);
    rcpp_result_gen = Rcpp::wrap(pmv_hoppe_iso(t, rh, wind, mtrad, iclo));
    return rcpp_result_gen;
END_RCPP
}
// pmv_holmer
double pmv_holmer(double Ta, double rh, double v, double Tr, double w, double Icl);
RcppExport SEXP biometeoR_pmv_holmer(SEXP TaSEXP, SEXP rhSEXP, SEXP vSEXP, SEXP TrSEXP, SEXP wSEXP, SEXP IclSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type Tr(TrSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type Icl(IclSEXP);
    rcpp_result_gen = Rcpp::wrap(pmv_holmer(Ta, rh, v, Tr, w, Icl));
    return rcpp_result_gen;
END_RCPP
}
// pmv_iso_7730
double pmv_iso_7730(double ta, double rh, double vel, double tr, double met, double wme, double clo);
RcppExport SEXP biometeoR_pmv_iso_7730(SEXP taSEXP, SEXP rhSEXP, SEXP velSEXP, SEXP trSEXP, SEXP metSEXP, SEXP wmeSEXP, SEXP cloSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ta(taSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type vel(velSEXP);
    Rcpp::traits::input_parameter< double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< double >::type met(metSEXP);
    Rcpp::traits::input_parameter< double >::type wme(wmeSEXP);
    Rcpp::traits::input_parameter< double >::type clo(cloSEXP);
    rcpp_result_gen = Rcpp::wrap(pmv_iso_7730(ta, rh, vel, tr, met, wme, clo));
    return rcpp_result_gen;
END_RCPP
}
// pmv_custom
double pmv_custom(double t, double rh, double wind, double mtrad, double met, double age, double ht, double mbody, double iclo);
RcppExport SEXP biometeoR_pmv_custom(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP, SEXP mtradSEXP, SEXP metSEXP, SEXP ageSEXP, SEXP htSEXP, SEXP mbodySEXP, SEXP icloSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type mtrad(mtradSEXP);
    Rcpp::traits::input_parameter< double >::type met(metSEXP);
    Rcpp::traits::input_parameter< double >::type age(ageSEXP);
    Rcpp::traits::input_parameter< double >::type ht(htSEXP);
    Rcpp::traits::input_parameter< double >::type mbody(mbodySEXP);
    Rcpp::traits::input_parameter< double >::type iclo(icloSEXP);
    rcpp_result_gen = Rcpp::wrap(pmv_custom(t, rh, wind, mtrad, met, age, ht, mbody, iclo));
    return rcpp_result_gen;
END_RCPP
}
// poda
double poda(double t, double rh, double p);
RcppExport SEXP biometeoR_poda(SEXP tSEXP, SEXP rhSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(poda(t, rh, p));
    return rcpp_result_gen;
END_RCPP
}
// thom
double thom(double t, double p_hPa);
RcppExport SEXP biometeoR_thom(SEXP tSEXP, SEXP p_hPaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type p_hPa(p_hPaSEXP);
    rcpp_result_gen = Rcpp::wrap(thom(t, p_hPa));
    return rcpp_result_gen;
END_RCPP
}
// utci
double utci(double t, double rh, double wind, double tmrt);
RcppExport SEXP biometeoR_utci(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP, SEXP tmrtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type tmrt(tmrtSEXP);
    rcpp_result_gen = Rcpp::wrap(utci(t, rh, wind, tmrt));
    return rcpp_result_gen;
END_RCPP
}
// wbgt
double wbgt(double t, double rh, double wind);
RcppExport SEXP biometeoR_wbgt(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    rcpp_result_gen = Rcpp::wrap(wbgt(t, rh, wind));
    return rcpp_result_gen;
END_RCPP
}
// proj
double proj(double sunelev);
RcppExport SEXP biometeoR_proj(SEXP sunelevSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sunelev(sunelevSEXP);
    rcpp_result_gen = Rcpp::wrap(proj(sunelev));
    return rcpp_result_gen;
END_RCPP
}
// temprad
double temprad(double t, double rh, double rshort, double rdiffuse, double sunelev, double albedo);
RcppExport SEXP biometeoR_temprad(SEXP tSEXP, SEXP rhSEXP, SEXP rshortSEXP, SEXP rdiffuseSEXP, SEXP sunelevSEXP, SEXP albedoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type rshort(rshortSEXP);
    Rcpp::traits::input_parameter< double >::type rdiffuse(rdiffuseSEXP);
    Rcpp::traits::input_parameter< double >::type sunelev(sunelevSEXP);
    Rcpp::traits::input_parameter< double >::type albedo(albedoSEXP);
    rcpp_result_gen = Rcpp::wrap(temprad(t, rh, rshort, rdiffuse, sunelev, albedo));
    return rcpp_result_gen;
END_RCPP
}
// humidex
double humidex(double t, double rh);
RcppExport SEXP biometeoR_humidex(SEXP tSEXP, SEXP rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    rcpp_result_gen = Rcpp::wrap(humidex(t, rh));
    return rcpp_result_gen;
END_RCPP
}
// hi
double hi(double t, double rh);
RcppExport SEXP biometeoR_hi(SEXP tSEXP, SEXP rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    rcpp_result_gen = Rcpp::wrap(hi(t, rh));
    return rcpp_result_gen;
END_RCPP
}
// net
double net(double t, double rh, double wind);
RcppExport SEXP biometeoR_net(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    rcpp_result_gen = Rcpp::wrap(net(t, rh, wind));
    return rcpp_result_gen;
END_RCPP
}
// ssi
double ssi(double t, double rh);
RcppExport SEXP biometeoR_ssi(SEXP tSEXP, SEXP rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    rcpp_result_gen = Rcpp::wrap(ssi(t, rh));
    return rcpp_result_gen;
END_RCPP
}
// steadman_outdoor_sun
double steadman_outdoor_sun(double t, double rh, double wind, double rshort, double sunelev);
RcppExport SEXP biometeoR_steadman_outdoor_sun(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP, SEXP rshortSEXP, SEXP sunelevSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type rshort(rshortSEXP);
    Rcpp::traits::input_parameter< double >::type sunelev(sunelevSEXP);
    rcpp_result_gen = Rcpp::wrap(steadman_outdoor_sun(t, rh, wind, rshort, sunelev));
    return rcpp_result_gen;
END_RCPP
}
// steadman_indoor
double steadman_indoor(double t, double rh);
RcppExport SEXP biometeoR_steadman_indoor(SEXP tSEXP, SEXP rhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    rcpp_result_gen = Rcpp::wrap(steadman_indoor(t, rh));
    return rcpp_result_gen;
END_RCPP
}
// steadman_outdoor_shade
double steadman_outdoor_shade(double t, double rh, double wind);
RcppExport SEXP biometeoR_steadman_outdoor_shade(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    rcpp_result_gen = Rcpp::wrap(steadman_outdoor_shade(t, rh, wind));
    return rcpp_result_gen;
END_RCPP
}
// radteoric
double radteoric(double lat, double model_time, double topography);
RcppExport SEXP biometeoR_radteoric(SEXP latSEXP, SEXP model_timeSEXP, SEXP topographySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lat(latSEXP);
    Rcpp::traits::input_parameter< double >::type model_time(model_timeSEXP);
    Rcpp::traits::input_parameter< double >::type topography(topographySEXP);
    rcpp_result_gen = Rcpp::wrap(radteoric(lat, model_time, topography));
    return rcpp_result_gen;
END_RCPP
}
// ppd
double ppd(double pmv);
RcppExport SEXP biometeoR_ppd(SEXP pmvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type pmv(pmvSEXP);
    rcpp_result_gen = Rcpp::wrap(ppd(pmv));
    return rcpp_result_gen;
END_RCPP
}
// new_windchill
double new_windchill(double t, double wind);
RcppExport SEXP biometeoR_new_windchill(SEXP tSEXP, SEXP windSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    rcpp_result_gen = Rcpp::wrap(new_windchill(t, wind));
    return rcpp_result_gen;
END_RCPP
}
// t_apparent_aus
double t_apparent_aus(double t, double rh, double wind);
RcppExport SEXP biometeoR_t_apparent_aus(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    rcpp_result_gen = Rcpp::wrap(t_apparent_aus(t, rh, wind));
    return rcpp_result_gen;
END_RCPP
}
// clomin
double clomin(double t, double rh, double wind, double trad);
RcppExport SEXP biometeoR_clomin(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP, SEXP tradSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type trad(tradSEXP);
    rcpp_result_gen = Rcpp::wrap(clomin(t, rh, wind, trad));
    return rcpp_result_gen;
END_RCPP
}
// clomax
double clomax(double t, double rh, double wind, double trad);
RcppExport SEXP biometeoR_clomax(SEXP tSEXP, SEXP rhSEXP, SEXP windSEXP, SEXP tradSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type trad(tradSEXP);
    rcpp_result_gen = Rcpp::wrap(clomax(t, rh, wind, trad));
    return rcpp_result_gen;
END_RCPP
}
// rdiffuse
double rdiffuse(double radteoric, double rshort);
RcppExport SEXP biometeoR_rdiffuse(SEXP radteoricSEXP, SEXP rshortSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type radteoric(radteoricSEXP);
    Rcpp::traits::input_parameter< double >::type rshort(rshortSEXP);
    rcpp_result_gen = Rcpp::wrap(rdiffuse(radteoric, rshort));
    return rcpp_result_gen;
END_RCPP
}
// ta_comfort
double ta_comfort(double rh, double iclo, double wind, double M, double H);
RcppExport SEXP biometeoR_ta_comfort(SEXP rhSEXP, SEXP icloSEXP, SEXP windSEXP, SEXP MSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type rh(rhSEXP);
    Rcpp::traits::input_parameter< double >::type iclo(icloSEXP);
    Rcpp::traits::input_parameter< double >::type wind(windSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(ta_comfort(rh, iclo, wind, M, H));
    return rcpp_result_gen;
END_RCPP
}
// dewpt
double dewpt(double t, double kpa);
RcppExport SEXP biometeoR_dewpt(SEXP tSEXP, SEXP kpaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type kpa(kpaSEXP);
    rcpp_result_gen = Rcpp::wrap(dewpt(t, kpa));
    return rcpp_result_gen;
END_RCPP
}
// psat
double psat(double tdb);
RcppExport SEXP biometeoR_psat(SEXP tdbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tdb(tdbSEXP);
    rcpp_result_gen = Rcpp::wrap(psat(tdb));
    return rcpp_result_gen;
END_RCPP
}
// enthal
double enthal(double tdb, double w);
RcppExport SEXP biometeoR_enthal(SEXP tdbSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tdb(tdbSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(enthal(tdb, w));
    return rcpp_result_gen;
END_RCPP
}
// spvol
double spvol(double tc, double w, double pa);
RcppExport SEXP biometeoR_spvol(SEXP tcSEXP, SEXP wSEXP, SEXP paSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tc(tcSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type pa(paSEXP);
    rcpp_result_gen = Rcpp::wrap(spvol(tc, w, pa));
    return rcpp_result_gen;
END_RCPP
}
// humrat
double humrat(double p, double pa);
RcppExport SEXP biometeoR_humrat(SEXP pSEXP, SEXP paSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type pa(paSEXP);
    rcpp_result_gen = Rcpp::wrap(humrat(p, pa));
    return rcpp_result_gen;
END_RCPP
}
// wetblb
double wetblb(double tstar, double w, double hh, double pa);
RcppExport SEXP biometeoR_wetblb(SEXP tstarSEXP, SEXP wSEXP, SEXP hhSEXP, SEXP paSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tstar(tstarSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type hh(hhSEXP);
    Rcpp::traits::input_parameter< double >::type pa(paSEXP);
    rcpp_result_gen = Rcpp::wrap(wetblb(tstar, w, hh, pa));
    return rcpp_result_gen;
END_RCPP
}
// relhum
double relhum(double mu, double pws, double pa);
RcppExport SEXP biometeoR_relhum(SEXP muSEXP, SEXP pwsSEXP, SEXP paSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type pws(pwsSEXP);
    Rcpp::traits::input_parameter< double >::type pa(paSEXP);
    rcpp_result_gen = Rcpp::wrap(relhum(mu, pws, pa));
    return rcpp_result_gen;
END_RCPP
}
// p_local
double p_local(double press, double topo, double temp);
RcppExport SEXP biometeoR_p_local(SEXP pressSEXP, SEXP topoSEXP, SEXP tempSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type press(pressSEXP);
    Rcpp::traits::input_parameter< double >::type topo(topoSEXP);
    Rcpp::traits::input_parameter< double >::type temp(tempSEXP);
    rcpp_result_gen = Rcpp::wrap(p_local(press, topo, temp));
    return rcpp_result_gen;
END_RCPP
}
