# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dewPoint <- function(celsius, humidity) {
    .Call('biometeoR_dewPoint', PACKAGE = 'biometeoR', celsius, humidity)
}

es <- function(ta) {
    .Call('biometeoR_es', PACKAGE = 'biometeoR', ta)
}

degsat <- function(t, rh, pa) {
    .Call('biometeoR_degsat', PACKAGE = 'biometeoR', t, rh, pa)
}

heatindex <- function(t, rh) {
    .Call('biometeoR_heatindex', PACKAGE = 'biometeoR', t, rh)
}

p_vap <- function(t, rh) {
    .Call('biometeoR_p_vap', PACKAGE = 'biometeoR', t, rh)
}

metabolism <- function(t) {
    .Call('biometeoR_metabolism', PACKAGE = 'biometeoR', t)
}

frostime <- function(t, wind) {
    .Call('biometeoR_frostime', PACKAGE = 'biometeoR', t, wind)
}

p_saturazione <- function(t) {
    .Call('biometeoR_p_saturazione', PACKAGE = 'biometeoR', t)
}

pmv_hoppe_iso <- function(t, rh, wind, mtrad, iclo) {
    .Call('biometeoR_pmv_hoppe_iso', PACKAGE = 'biometeoR', t, rh, wind, mtrad, iclo)
}

pmv_holmer <- function(Ta, rh, v, Tr, w, Icl) {
    .Call('biometeoR_pmv_holmer', PACKAGE = 'biometeoR', Ta, rh, v, Tr, w, Icl)
}

pmv_iso_7730 <- function(ta, rh, vel, tr, met, wme, clo) {
    .Call('biometeoR_pmv_iso_7730', PACKAGE = 'biometeoR', ta, rh, vel, tr, met, wme, clo)
}

pmv_custom <- function(t, rh, wind, mtrad, met, age, ht, mbody, iclo) {
    .Call('biometeoR_pmv_custom', PACKAGE = 'biometeoR', t, rh, wind, mtrad, met, age, ht, mbody, iclo)
}

poda <- function(t, rh, p) {
    .Call('biometeoR_poda', PACKAGE = 'biometeoR', t, rh, p)
}

thom <- function(t, p_hPa) {
    .Call('biometeoR_thom', PACKAGE = 'biometeoR', t, p_hPa)
}

utci <- function(t, rh, wind, tmrt) {
    .Call('biometeoR_utci', PACKAGE = 'biometeoR', t, rh, wind, tmrt)
}

wbgt <- function(t, rh, wind) {
    .Call('biometeoR_wbgt', PACKAGE = 'biometeoR', t, rh, wind)
}

proj <- function(sunelev) {
    .Call('biometeoR_proj', PACKAGE = 'biometeoR', sunelev)
}

temprad <- function(t, rh, rshort, rdiffuse, sunelev, albedo) {
    .Call('biometeoR_temprad', PACKAGE = 'biometeoR', t, rh, rshort, rdiffuse, sunelev, albedo)
}

humidex <- function(t, rh) {
    .Call('biometeoR_humidex', PACKAGE = 'biometeoR', t, rh)
}

hi <- function(t, rh) {
    .Call('biometeoR_hi', PACKAGE = 'biometeoR', t, rh)
}

net <- function(t, rh, wind) {
    .Call('biometeoR_net', PACKAGE = 'biometeoR', t, rh, wind)
}

ssi <- function(t, rh) {
    .Call('biometeoR_ssi', PACKAGE = 'biometeoR', t, rh)
}

steadman_outdoor_sun <- function(t, rh, wind, rshort, sunelev) {
    .Call('biometeoR_steadman_outdoor_sun', PACKAGE = 'biometeoR', t, rh, wind, rshort, sunelev)
}

steadman_indoor <- function(t, rh) {
    .Call('biometeoR_steadman_indoor', PACKAGE = 'biometeoR', t, rh)
}

steadman_outdoor_shade <- function(t, rh, wind) {
    .Call('biometeoR_steadman_outdoor_shade', PACKAGE = 'biometeoR', t, rh, wind)
}

radteoric <- function(lat, model_time, topography) {
    .Call('biometeoR_radteoric', PACKAGE = 'biometeoR', lat, model_time, topography)
}

ppd <- function(pmv) {
    .Call('biometeoR_ppd', PACKAGE = 'biometeoR', pmv)
}

new_windchill <- function(t, wind) {
    .Call('biometeoR_new_windchill', PACKAGE = 'biometeoR', t, wind)
}

t_apparent_aus <- function(t, rh, wind) {
    .Call('biometeoR_t_apparent_aus', PACKAGE = 'biometeoR', t, rh, wind)
}

clomin <- function(t, rh, wind, trad) {
    .Call('biometeoR_clomin', PACKAGE = 'biometeoR', t, rh, wind, trad)
}

clomax <- function(t, rh, wind, trad) {
    .Call('biometeoR_clomax', PACKAGE = 'biometeoR', t, rh, wind, trad)
}

rdiffuse <- function(radteoric, rshort) {
    .Call('biometeoR_rdiffuse', PACKAGE = 'biometeoR', radteoric, rshort)
}

ta_comfort <- function(rh, iclo, wind, M, H) {
    .Call('biometeoR_ta_comfort', PACKAGE = 'biometeoR', rh, iclo, wind, M, H)
}

dewpt <- function(t, kpa) {
    .Call('biometeoR_dewpt', PACKAGE = 'biometeoR', t, kpa)
}

psat <- function(tdb) {
    .Call('biometeoR_psat', PACKAGE = 'biometeoR', tdb)
}

enthal <- function(tdb, w) {
    .Call('biometeoR_enthal', PACKAGE = 'biometeoR', tdb, w)
}

spvol <- function(tc, w, pa) {
    .Call('biometeoR_spvol', PACKAGE = 'biometeoR', tc, w, pa)
}

humrat <- function(p, pa) {
    .Call('biometeoR_humrat', PACKAGE = 'biometeoR', p, pa)
}

wetblb <- function(tstar, w, hh, pa) {
    .Call('biometeoR_wetblb', PACKAGE = 'biometeoR', tstar, w, hh, pa)
}

relhum <- function(mu, pws, pa) {
    .Call('biometeoR_relhum', PACKAGE = 'biometeoR', mu, pws, pa)
}

p_local <- function(press, topo, temp) {
    .Call('biometeoR_p_local', PACKAGE = 'biometeoR', press, topo, temp)
}

